In [45]:
import pandas as pd

df = pd.read_csv('amazon_delivery.csv')
df

            Order_ID  Agent_Age  Agent_Rating  Store_Latitude  ...      Vehicle            Area  Delivery_Time     Category
0      ialx566343618         37           4.9       22.745049  ...  motorcycle           Urban             120     Clothing
1      akqg208421122         34           4.5       12.913041  ...     scooter   Metropolitian             165  Electronics
2      njpu434582536         23           4.4       12.914264  ...  motorcycle           Urban             130       Sports
3      rjto796129700         38           4.7       11.003669  ...  motorcycle   Metropolitian             105    Cosmetics
4      zguw716275638         32           4.6       12.972793  ...     scooter   Metropolitian             150         Toys
...              ...        ...           ...             ...  ...          ...             ...            ...          ...
43734  jlxf819993117         30           4.8       26.902328  ...  motorcycle   Metropolitian             160         Home
43735  aevx342135787         21           4.6        0.000000  ...  motorcycle   Metropolitian             180      Jewelry
43736  xnek760674819         30           4.9       13.022394  ...     scooter   Metropolitian              80         Home
43737  cynl434665991         20           4.7       11.001753  ...  motorcycle   Metropolitian             130      Kitchen
43738  nsyz997960170         23           4.9       23.351058  ...     scooter   Metropolitian             180    Cosmetics

[43739 rows x 16 columns]

In [46]:
df = df.drop(['Order_ID', 'Pickup_Time'], axis=1)

In [47]:
import datetime as dt
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['day_of_week'] = df['Order_Date'].dt.dayofweek

df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)

df['month'] = df['Order_Date'].dt.month

df['Order_Time'] = pd.to_datetime(df['Order_Time'], format= '%H:%M:%S', errors='coerce')

df['hour'] = df['Order_Time'].dt.hour

df['order_hour_block'] = pd.cut(df['hour'], bins=[0, 6, 12, 18, 24], labels=('night', 'morning', 'afternoon', 'evening'))

df['is_fast_delivery'] = (df['Delivery_Time'] >= df['Delivery_Time'].median()).astype(int)

## The columns 'Order_Date', and 'Date_time' served their purpose. Having successfuly extracted the needed information from those columns, I can drop them without hesitation.

In [48]:
df = df.drop(['Order_Date', 'Order_Time', 'hour'], axis=1)

In [49]:
df.head()

   Agent_Age  Agent_Rating  Store_Latitude  Store_Longitude  ...  is_weekend  month order_hour_block is_fast_delivery
0         37           4.9       22.745049        75.892471  ...           1      3          morning                0
1         34           4.5       12.913041        77.683237  ...           0      3          evening                1
2         23           4.4       12.914264        77.678400  ...           1      3          morning                1
3         38           4.7       11.003669        76.976494  ...           0      4        afternoon                0
4         32           4.6       12.972793        80.249982  ...           1      3        afternoon                1

[5 rows x 17 columns]